services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=pg
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      - DB=postgres://pg:pg@localhost:5432/pg
      - IMAGE_KIT_PRIVATE_KEY=private_EzLNfUiJr3B4YgTKLAHYBdIG6fQ=
    depends_on:
      - db
volumes:
  postgres:
